test_sentences = [
    ["Ongi tõestatud, et inimene on tööl palju produktiivsem, kui talle antakse ka aega oma kodustega olla, kui ta ei pea liigselt üle töötama.Kõik sellised asjad."],
    ["Ja ka oskus kuulata sageli ju aitab."],
    ["Vähemalt ma arvan, et mures olijat aitab väga palju see, kui keegi teda lihtsalt kuulab ja on olemas."],
    ["Aga inimesed ei oska seda teha sageli."],
    ["Mul on tunne, et tegelikult me kõik vajame mingi hetk seda kohta, kus me saamegi vastutuse ära anda."],
    ["See ei ole tegelikult üldse halb."],
    ["See on osa elust ja me igaüks vajame seda."],
    ["Mulle meeldib ka otsustada, mulle meeldib ka vastutada."],
    ["Mul ei ole midagi selle vastu, aga vahepeal on tunne, et ma tahan, et keegi lihtsalt minu eest mingid asjad ära teeks."],
    ["Sest tegelikult, kui ma vaatan praegu tagasi, meil on nii ägedad kaks kuud olnud selles maamajakeses."],
    ["Teeme kaminat, ja me ei vaata enam nii palju telekat."],
    ["ee noh kindlasti sina oled üks väheseid ee pigem väheseid inimesi, kes oskab kuulata ja oskab seda nii-öelda mingisugust nõu anda või lohutust anda."],
    ["Aga paljud ei oskagi, nad jäävad kohmetuks."],
    ["Aga kui nüüd ee mõelda vananemise peale, siis ee noh, me muutume aasta-aastalt vanemaks, targemaks ka muidugi."],
    ["Ilusamaks ka, ma loodan."],
    ["ee mina küll tunnen, et ma nagu, mõnes mõttes lähen aastatega paremaks."],
    ["ee ja siis mul oli küll muide see mõte et ee."],
    ["Ma olen alati mõelnud, et ma tahaks ee seda inimest nagu rohkem ee tunda, või nagu saanud tunda tol hetkel."],
    ["Et selles suhtes on, see kirjaidee on küll noh päris ee tore."],
    ["Ta rääkis täpselt seda, mida nagu mina olin nagu mõelnud, aga tema lihtsalt pani selle palju paremini nagu sõnadesse ja oskas seda nii ilusasti nagu serveerida."],
    ["Ma siiamaani mõtlen selle peale."],
    ["Me oleme teineteisele väga palju praktilisi asju ka kinkinud ja ja teinud ee siin-seal mingeid ee selliseid väikseid üllatusi."],
    ["Ja ja need on ka vajalikud."]
]